### ISSUE TITLE
Update most if not all notebooks

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqTutorials.jl#33]
@ChrisRackauckas Can you or someone please update most if not all notebooks in DiffEqTutorials to run smoothly on current Julia v1.0.1 and DifferentialEquations v5.3.1. For a fruitful dissemination of Julia DiffEq, it is important that this collection of notebooks runs flawlessly.

**Comment by ChrisRackauckas** [comment]
Indeed. In fact, I want to remove the notebooks and instead make this all pdfs and notebooks generated by Weave.jl. I think that would be a lot more maintainable.

**Comment by HenriLaurie** [comment]
I think this has become urgent (well, a bit selfishly, I am due to teach Julia and JuliaDiffEq in 4 weeks time). I'd like to make a start, at least with the intro notebooks, and can see easy changes for all except the code-optimisations ... but now what about Weave.jl?

I like the idea of a weave, but have never actually walked the talk of writing code and documentation as one.

If we are to go to Weave I can see two problems
--- Weave is not working properly for me (am on v1.1, Weave's tests say they pass but they do throw warnings and error messages, the examples from the Weave repository rely on Gadfly which doesn't currently pass tests and doesn't precompile when I try using it).
--- I am confused by all the options in Weave and in particular do not have a workflow/environment where I can edit, run the code, and preview the rendering of pdf and html output.

I'd suggest separating the two: people like me start updating the notebooks, and some-one with expertise in Weave.jl takes the initiative with that.

**Comment by ChrisRackauckas** [comment]
I do have a branch I was working on: https://github.com/JuliaDiffEq/DiffEqTutorials.jl . Let me push some of the updated notebooks this weekend.

**Comment by ChrisRackauckas** [comment]
This PR has the updates for the introduction notebooks already done: https://github.com/JuliaDiffEq/DiffEqTutorials.jl/pull/36

**Comment by ChrisRackauckas** [comment]
Everything has a translation, a few of them need to get finished.

**Comment by HenriLaurie** [comment]
By translation I guess you mean to weave? I viewed the conversation on #36
but am not sure how I could view the notebooks, do I need to wait for the
PR to go through to master? I will certainly read/test them as soon as they
come through (well, as soon as I see they're there), anything else I could
do?

**Comment by ChrisRackauckas** [comment]
Do you still want notebooks? Or are PDFs and webpages good? We can output notebooks but for now I was just building the two former

**Comment by HenriLaurie** [comment]
Well, I could go on with pdf/html but notebooks are definitely better,
they're so much easier to play with, superb for teaching.

**Comment by ChrisRackauckas** [comment]
Complete.

@HenriLaurie there are some issues with Weave.jl's notebook output which we can track here: https://github.com/JuliaDiffEq/DiffEqTutorials.jl/issues/37 . But other than that, everything is updated to v1.0 so I'm closing this.

**Comment by ChrisRackauckas** [comment]
@HenriLaurie Notebook output has been fixed. There's a small rendering issue that'll get fixed soon in Weave and then that'll be good to go.
